# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Officials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('lgas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikipol1.LGAs')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='officials',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikipol1.Position'),
        ),
        migrations.AddField(
            model_name='lgas',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikipol1.State'),
        ),
    ]
